import type { Metadata } from "next";
import Font from "next/font/local";
import "./globals.css";

const inter = Font({ src: "../fonts/Inter/Inter-VariableFont_slnt,wght.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
